apiVersion: v1
kind: Service
metadata:
  name: cortex-connection-test
  namespace: cortex
  labels:
    app.kubernetes.io/component: cortex-connection-test
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/component: cortex-connection-test
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: cortex-connection-test
  name: cortex-member
  namespace: cortex
spec:
  serviceName: cortex-connection-test
  replicas: 2
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app.kubernetes.io/component: cortex-connection-test
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: cortex-connection-test
    spec:
      containers:
        - name: connection-test
          image: "andrejbranch/connection-test:main-2021-09-10-91961e3"
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: "500m"
              memory: "100Mi"
          securityContext:
            readOnlyRootFilesystem: true
      terminationGracePeriodSeconds: 30